---
name: "Support"
description: "Ask a question, get help with the integration"
labels: "question"
body:
- type: markdown
  attributes:
    value: Before you open a new issue, search through the existing issues to see if others have had the same problem.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I need support with using the integration.
        required: true
      - label: This is not a bug report avoiding the [bug report](https://github.com/safepay/hdpv_ble/issues/new?assignees=&labels=Bug&projects=&template=bug.yml) form.
        required: true
- type: textarea
  attributes:
    label: "Describe the issue"
    description: "Please describe your issue, ask your question and give necessary context (shade type ID, whether you use a Bluetooth proxy or a PowerView hub)."
  validations:
    required: true
